### ISSUE TITLE
Баг: Проект не собирается через docker-compose up

### ISSUE THREAD

**Issue by noroot** [vas3k/vas3k.club#776]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

`$ sudo docker-compose up`

```
Building queue
Sending build context to Docker daemon  13.71MB

Step 1/11 : FROM ubuntu:20.04
 ---> ba6acccedd29
Step 2/11 : ENV MODE dev
 ---> Using cache
 ---> a8901b658f80
Step 3/11 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 689a7a06bfdf
Step 4/11 : RUN apt-get update     && apt-get install --no-install-recommends -yq       python3       python3-pip       libpq-dev       gdal-bin       libgdal-dev       make     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> bfd3223eaecc
Step 5/11 : WORKDIR /app
 ---> Using cache
 ---> b7f0bed96303
Step 6/11 : COPY . /app
 ---> Using cache
 ---> 00cfabaa8d2e
Step 7/11 : RUN pip3 install pipenv
 ---> Using cache
 ---> 48a88c7c6e48
Step 8/11 : RUN sh -c 'if [ "$MODE" = 'production' ]; then pipenv lock --keep-outdated --requirements > requirements.txt; fi'
 ---> Using cache
 ---> 2a0e8b9d07f7
Step 9/11 : RUN sh -c 'if [ "$MODE" = 'dev' ]; then pipenv lock --dev --requirements > requirements.txt; fi'
 ---> Running in 41aace8c10f7
/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /app/Pipfile
Using /usr/bin/python3.8 (3.8.10) to create virtualenv...

⠋ Creating virtual environment...
⠙ Creating virtual environment...
⠹ Creating virtual environment...
⠸ Creating virtual environment...
⠼ Creating virtual environment...
⠴ Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 327ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/app-4PlAip0Q, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==58.3.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/app-4PlAip0Q
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/cli/command.py", line 344, in lock
    do_init(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 1255, in do_init
    do_install_dependencies(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 796, in do_install_dependencies
    deps = [
  File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 797, in <listcomp>
    req.as_line(sources=False, include_hashes=False) for req in deps_list
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2795, in as_line
    assert self.line_instance is not None
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2553, in line_instance
    self.line_instance = self.get_line_instance()
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2547, in get_line_instance
    return Line(line)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 171, in __init__
    self.parse()
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1289, in parse
    self.parse_extras()
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 577, in parse_extras
    self.line, extras = pip_shims.shims._strip_extras(self.line)
TypeError: 'NoneType' object is not callable
The command '/bin/sh -c sh -c 'if [ "$MODE" = 'dev' ]; then pipenv lock --dev --requirements > requirements.txt; fi'' returned a non-zero code: 1
ERROR: Service 'queue' failed to build

```
Окружение:
* 5.13.12-200.fc34.x86_64
* docker-compose version 1.25.5, build unknown
* Docker version 20.10.3, build 48d30b5

## Ожидаемый результат

Должно устаналиваться из коробки как написано в README

## Шаги к воспроизведению
$ git clone https://github.com/vas3k/vas3k.club/
$ sudo docker-compose up

**Comment by devcooch** [comment]
А почему sudo?

**Comment by noroot** [comment]
@devcooch потому что docker.sock был рутовый, но сути не меняет, после `sudo chown $USER /var/run/docker.sock`
ошибка воспроизводится и без sudo

**Comment by noroot** [comment]
Еще артефактов

`docker info `

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 67
  Running: 0
  Paused: 0
  Stopped: 67
 Images: 135
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.12-200.fc34.x86_64
 Operating System: Fedora 34 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.28GiB
 Name: ****
 ID: ********
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by glader** [comment]
У меня точно такая же ошибка в [сборке](https://github.com/glader/4aff.club/runs/4126085829?check_suite_focus=true). 5го ноября обновился pipenv. Мне пришлось зафиксировать версию в Dockerfile
`RUN pip3 install pipenv==2021.5.29`

**Comment by vas3k** [comment]
Спасибо за фикс! Ща проверим
